### ISSUE TITLE
Does this library require PHP 8.1 ?

### ISSUE THREAD

**Issue by lostpebble** [xaevik/php-cuid2#3]
Hi,

Was wondering if there is a strict reason why 8.1 is the requirement for this library. We have old Wordpress sites that still run on 7.x or 8.0, which means this library is incompatible.

If there is no specific reason for 8.1- would you mind reducing that requirement to 8.0 (or 7.x if that's possible, even).

Your cuid library is the only one which doesn't seem to use `getmypid` which is great! Some Wordpress hosts seem to disable that for some reason. So I'd very much like to use your library.

**Comment by xaevik** [comment]
Hi @lostpebble 

There is no strict reason no, only other than PHP 8 is technically EOL. 

However, with that said, I will bump it down to 8.0 as I'm actually about to push out another release.

**Comment by lostpebble** [comment]
Okay, great! Thanks

**Comment by lostpebble** [comment]
![image](https://user-images.githubusercontent.com/1508863/214631889-8165fc26-0e6d-4dd6-8c4d-4e819e7bdbf3.png)

Actually just changed my PHP version to 8.0 in my IDE, and noticed this. So perhaps 8.1 is required?

**Comment by xaevik** [comment]
Yes, readonly properties were introduced in 8.1, however, they are not required and I'll refactor that to use psalm to indicate they are readonly. 

You mentioned that some hosts are disabling `getmypid`, the newer release (1.2.0) does use this but fallbacks if it returns `false`. Do they throw an actual error or does it just return `false`?

**Comment by lostpebble** [comment]
![image](https://user-images.githubusercontent.com/1508863/214633379-8b80a7ac-d157-476e-a538-659c7de05344.png)

This was the error I was getting while using CaliCastle\Cuid - I did some research and could see some people complaining about that method being missing on some hosts. So I just replaced it with your library. I'm using 1.0.0 and its working fine so far

**Comment by xaevik** [comment]
Ah I see, should be easy to work around that problem for environments that don't have access to it.

**Comment by xaevik** [comment]
@lostpebble I just pushed out 1.3.0-beta1 which changes the minimum supported version to PHP 8.0.x and adds some guards for `getmypid` and `gethostname`. Give that a shot and see if it will work for your needs.

**Comment by lostpebble** [comment]
Awesome! Will test it out now

**Comment by lostpebble** [comment]
![image](https://user-images.githubusercontent.com/1508863/214638744-bd54ca68-44e9-4df3-8c68-94c8c2e7923e.png)

Unfortunately running into this issue- could you remove the `readonly` keywords ? That removed this error when I did it manually.

**Comment by xaevik** [comment]
Strange that it would be evaluating that. What happens if you use `@psalm-readonly`?

**Comment by lostpebble** [comment]
Well its more that PHP 8.0 can't seem to understand this properly:

```php
private readonly int $counter;
```

Seems like having two "modifiers" like `readonly int` before the identifier is causing issues. Its reading `int` as the identifier by its not in variable syntax, hence the error.

I'm not quite sure what `@psalm-readonly` is and how to use it

**Comment by xaevik** [comment]
Strange that keyword should not be there, it was removed. Let me push out another build.

**Comment by xaevik** [comment]
I just pushed 1.3.0-beta2, should be good now.

**Comment by lostpebble** [comment]
Great, that seems to have solved that error!

**Comment by xaevik** [comment]
Great. I've pushed out 1.3.0 as a stable release, you should be good to go.

**Comment by xaevik** [comment]
@lostpebble in-case it is needed (because I actually needed it for an internal project), support has been added for 7.4.x as well.
