### ISSUE TITLE
Type error in hash_update() function

### ISSUE THREAD

**Issue by lostpebble** [xaevik/php-cuid2#5]
![image](https://user-images.githubusercontent.com/1508863/214643522-3cc13bdb-9b1a-4c03-a61b-1650eca15de0.png)

Seems like there is some kind of runtime error inside `FingerPrint.php`

**Comment by lostpebble** [comment]
![image](https://user-images.githubusercontent.com/1508863/214644220-a600ec24-1852-455a-8975-f05ff06edde3.png)

I think its a typo here- on the `$process` fallback

**Comment by xaevik** [comment]
Oops this is the price I pay for not updating the unit tests. Let me get that fixed.

**Comment by xaevik** [comment]
@lostpebble this has been resolved in release 1.3.1

**Comment by lostpebble** [comment]
Great- thanks for such quick resolutions!
